### PR TITLE
Add docker desktop support, tested on macOS Sonoma

### PR DESCRIPTION
**Pull request by antojoseph**
Hi ,

On Docker Desktop,  the IP's allocated to EL/CL clients are not accessible to  the host. As such, when you try `make devnet-run` , you do get dora on 12.0.0.1:8080, but it can't reach any clients. 

The Fix
I have added a bash script ` run_dd.sh` to `.hack/devnet` directory. This script bootstraps dora with the local ip and correct ports for EL/CL clients on docker desktop. I have also added a `devnetdd` and `devnetdd-run` command to the Make file so developers can quickly iterate on this. 

Please let me know if there are any questions. Adding screenshot of dora running with the `devnetdd-run` command in this PR
Screenshot 2024-07-27 at 3 49 52 AM

### CODE REVIEW

**Comment by antojoseph** [comment]
You can ignore the changes in `run.sh`, I mainly used it for testing :)

**Comment by antojoseph** [comment]
Thanks @skylenet for the review. This does make sense. I will update the PR shortly :)

**Comment by antojoseph** [comment]
@skylenet Updated PR with changes to just run.sh file. LMK if this looks good.

**Comment by pk910** [comment]
works fine for me (debian + docker daemon)

**Review by skylenet — APPROVED** [review]

**Pull request merged**
